### ISSUE TITLE
Sideloading big apps don’t work.

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#131]
Currently when you sideload big apps like retroarch without modifying currently never finishes. AltStore has this issue before but I do see people want that fixed for big apps like it.

**Comment by jkcoxson** [comment]
What do the logs stop on?

**Comment by jrew20** [comment]
I have the same problem. Tried to install apps with size of 1.6gb, first it starts but in the middle of installing the same error appears which is "unknown error occurred". hoping this would be fixed on the next update because i love to use sidestore now since its easy to use and its open source. thank!

![662DA5D9-7DFD-4DC7-A1A8-D86ACAEADD98](https://user-images.githubusercontent.com/84695520/205192297-15ebf7b1-ab65-4329-b936-4b5d73f22109.png)
![67C045E4-9D5B-4F05-88F2-DDF4DEC60248](https://user-images.githubusercontent.com/84695520/205192300-b858f864-22c8-4e25-a036-1b6ed233365f.png)

**Comment by LeeHerrmann** [comment]
So how it goes now?
