### ISSUE TITLE
[Developer Request] Change the anisette data logic for newer server idea

### ISSUE THREAD

**Issue by Nythepegasus** [SideStore/SideStore#191]
I have an anisette server wrapper that I have written in Python that could solve all of our anisette woes. The current idea requires some extra logic to be written into SideStore though. Here's the layout:

---

First make a GET request to the anisette server to acquire a personalized `adi.pb` file 
(ex. `GET http://127.0.0.1:6969/adi_file`)

We save this `adi.pb` file somewhere SideStore can keep it forever. We could also give users the option to clear this file if they feel it has become outdated/nonfunctional.

Secondly, every subsequent request to the anisette servers should theoretically only be POST requests 
(ex. `POST http://127.0.0.1:6969/anisette`) 

The server will use that `adi.pb` to generate the client their personalized anisette. 

Edit: The file to edit for this is AltStore/Operations/FetchAnisetteOperation.Swift, it has all the functionality for requesting for anisette.

**Comment by lonkelle** [comment]
To make this even easier for @JoeMatt, wanted to add this link to the exact line the new code would start: https://github.com/SideStore/SideStore/blob/6f519c97d372d08913ac11fcd81beb171906c105/AltStore/Operations/FetchAnisetteDataOperation.swift#L38

**Comment by f1shy-dev** [comment]
What exactly would be stored in thé `adi.pb` or similar file?

**Comment by lonkelle** [comment]
@f1shy-dev Essentially an “anisette fingerprint” that can be linked to an individual device to be used to constantly regenerate the same anisette headers. @Nythepegasus can explain it best tho?

**Comment by lonkelle** [comment]
Changing this to Official Release because we can't deal with lockout backlash when we make SideStore official (our of alpha / beta). 

@Nythepegasus What can the team do to help you finish this specific task up? We'll do whatever we can. This is incredibly important as lockout issues scare tf out of laymen users and some tech users. And we're supposed to be as easy for a laymen as possible. At least, that's what I've been striving for. Hope we're doing it. 😅
