### ISSUE TITLE
how can I install it with macOS

### ISSUE THREAD

**Issue by ls114513** [SideStore/SideStore#206]

**Comment by powenn** [comment]
Just use sideload methods like AltServer (option click to direct install) or sideloadly 
,and you'll need pair file from jutterbug and vpn conf file in release

**Comment by lonkelle** [comment]
Sideloadly doesn't work yet to to sideload SideStore. The macOS SideServer is practically done. Just two more small things and auto-installing SideStore on macOS will be a simple one click operation. 

Next is a Linux SideServer based on AltLinux and a Windows SideServer based on...we might just write that from scratch since no one can build AltServer for Windows to fork off and convert it into a SideServer. 

Will comment back on this issue with the macOS build when it's finished in a couple days. 💜
