### ISSUE TITLE
[BUG] 2FA needed for refresh, install or view app IDs

### ISSUE THREAD

**Issue by Clayton630** [SideStore/SideStore#232]
**Describe the bug**
Always need to log in on iPhone

**To Reproduce**
I installed Sidestore on both my iPhone and my iPad. On my iPhone, everytime I want to refresh my apps, see app ids or side load a new app, it asks for the 2 factors authentication code. I don't have the issue on my iPad

**Expected behavior**
I should only log in once

**Comment by naturecodevoid** [comment]
This is most likely because of the anisette server you are using. Have you tried switching anisette server or using your own anisette server? You can find a guide for making your own server at https://wiki.sidestore.io/guides/custom-anisette

Also, what build are you using? Nightly, 0.1.1 or another test build?

**Comment by Blockr22** [comment]
This happens to me on my iPhone 14, i m using latest SideStore nightly 7 & my own render.com anisette server.

**Comment by JanCraft** [comment]
Anisette hosted on render.com turns off after a few minutes, I think that causes it to require 2FA again.

**Comment by Blockr22** [comment]
@JanCraft Then there should be anisette server that works without 2fa, none of the default anisette servers works

**Comment by ladjeek-actions** [comment]
> Anisette hosted on render.com turns off after a few minutes, I think that causes it to require 2FA again.

If so, we can use cloudflare worker's cronjob or uptimerobot to stay active

**Comment by Blockr22** [comment]
@ladjeek-actions can u plz explain what are these services & how can i use it to make that render.com server active all the time ?

**Comment by ladjeek-actions** [comment]
> @ladjeek-actions can u plz explain what are these services & how can i use it to make that render.com server active all the time ?

You can think of them as services that periodically send requests to the render server

Deceive render in such a way

**Comment by ringosham** [comment]
The issue is that cloud services your service across several virtual machines and servers

If the cloud provider migrates your anisette server to another machine for maintenance, it counts as another Mac for Apple.

Sidenote: Do not use Google cloud compute. Google frequently moves your service around. Sidestore keeps trying to login but fails because of 2FA. Eventually Apple just unsigns your Sidestore app.

**Comment by Spidy123222** [comment]
Since this is a server hosting issue this will be closed
