### ISSUE TITLE
[BUG] Incorrect verification code for all servers

### ISSUE THREAD

**Issue by zeroxoneafour** [SideStore/SideStore#287]
### Describe the bug

I cannot log into any anisette servers with my iCloud account. I have tried my main account, 1 old burner account, and 1 new burner account, all of which failed. The failure happens during the 2fa part of logging in, which always says "Incorrect verification code" whether the code is correct or not. I have tried this with the Sideloadly, AltStore, and SideStore backends, as well as both the develop and main branches of Provision hosted on Render. The AltStore AltServer backend stays loading forever and never asks for 2fa nor logs in successfully.

I think that this is an issue with SideStore or possibly Provision because anisette works with all of my accounts when I sideload things using AltStore or Sideloadly.

### Instructions to reproduce

1. Try to login
2. Enter verification code that was sent to your Apple device
3. It doesn't work

### What version of SideStore are you using?

0.3.1

**Comment by naturecodevoid** [comment]
1. Have you tried [self hosting an anisette server?](https://wiki.sidestore.io/guides/custom-anisette.html)
2. Do you have advanced data protection on?

**Comment by zeroxoneafour** [comment]
I have tried self hosting by forking the repo (I didn't rename it, but Render built and ran it successfully). I don't think ADP is on because Apple's support website says it's only available for 16.2 and up, and I am running 16.1.

**Comment by naturecodevoid** [comment]
No idea what the issue is. However, V3 of the anisette server has been completed and all that's left is implementing it in SideStore. This should fix most, if not all anisette problems. If you want to be one of the alpha testers for this, you can [join our discord](https://discord.gg/CacsuuzsBq) (make sure to get the SideStore Testers role so you get pinged). Hopefully we will have it working with SideStore within a few days.

**Comment by zeroxoneafour** [comment]
Worked when using https://ani.sidestore.io as the custom URL
