### ISSUE TITLE
[BUG] Cannot refresh apps

### ISSUE THREAD

**Issue by Stillbadatlinux** [SideStore/SideStore#430]
### Describe the bug

When I try to refresh it gives me this error The operation couldn’t be completed. An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.). Please try again. If the issue persists, report it on GitHub Issues!

### Instructions to reproduce

I don’t know

### What version of SideStore are you using?

0.40 nightly

**Comment by Zhou-Shilin** [comment]
You should check the discord.
spidy12322: If any of you are having issues with refreshing and Sideloading because of the message “An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down”

If you get this message and is using sidestore preset (default preset) in settings for ansiette. Please change the server manually by adding  https://ani.sidestore.io/ to “Anisette URL” box and disable preferred servers for the meantime. We will do an update soon to fix the problem. 

To find this setting go to the settings app then to SideStore. This is where you add the anisette url and disable preferred servers. 

![baimoqilin.top](https://github.com/SideStore/SideStore/assets/17764867/3912d58a-d964-4685-b82d-a448a9888127)
