### ISSUE TITLE
[BUG] Background refresh not working

### ISSUE THREAD

**Issue by JaiveerSafri** [SideStore/SideStore#496]
### Describe the bug

For whatever reason, on several devices, the normal refresh works great, however seems to not refresh in the background, resulting in the 7 day limit ending and having to reinstall it manually. I am using the preset anisette server and iOS 17, though this has been an issue on iOS 16 too.

### Instructions to reproduce

Let the vpn run in the background always and it sometimes will just not refresh in the background.

### What version of SideStore are you using?

0.5.1

**Comment by naturecodevoid** [comment]
Did you turn off background refresh or use low power mode?

**Comment by JaiveerSafri** [comment]
> Did you turn off background refresh or use low power mode?

Low battery mode is off and background refresh is always on.

**Comment by Spidy123222** [comment]
You still need to use the device as it can only do the action when you it's unlocked.

**Comment by jimmysofat6864** [comment]
You can use the iOS shortcuts to automate a refresh at a specific time. As long as you have Wireguard set to on demand you should be good.

**Comment by akshaydogra1** [comment]
@jimmysofat6864 , can you please elaborate on how that is setup? i am trying to automate this as well.

**Comment by jimmysofat6864** [comment]
> @jimmysofat6864 , can you please elaborate on how that is setup? i am trying to automate this as well.

@akshaydogra1 All I did was open the shortcuts app and then go to all shortcuts, then press the plus button at the top right and select add action. Then go to apps and search for sidestore and select refresh all apps. Then once you have that shortcut set up just press the play button to make sure it's working. If you get an error about timing out that sometimes happens but if you get an error saying "The file doesn't exist" like I did, you need to generate a pairing file and put it in the right place as described here https://docs.sidestore.io/docs/getting-started/pairing-file. 

Then in the shortcuts app, select automations at the bottom of the screen and then set your desired time to have a refresh. Make sure options to run immediately and notify when run is enabled.Then if all goes well it should work as I've had this going for months and no problems as of yet. 

BTW I have it set to run twice because sometimes the first time it doesn't work because of the timeout issue I mentioned and you may see that but usually the second time it does work. You can see how I have it done below. Also for this to work you must have WireGuard setting for SideStore set to on demand activation on Wi-Fi just in case WireGuard closes for some reason. And that should be it. 


![IMG_F2AE01832172-1](https://github.com/SideStore/SideStore/assets/69532417/ff4502ec-a9a6-4cbb-8a84-752ad6199f9c)

**Comment by jimmysofat6864** [comment]
@akshaydogra1 actually just follow the Reddit guide as it more detailed. https://www.reddit.com/r/sideloaded/comments/1bxyx9j/guide_how_to_automate_sidestore_refreshes/

**Comment by akshaydogra1** [comment]
@jimmysofat6864 , thank you. This helps :)
