### ISSUE TITLE
[BUG] SideStore freezes

### ISSUE THREAD

**Issue by alx080** [SideStore/SideStore#497]
### Describe the bug

Updated to iOS 17.1, had to enter 2FA in the app again, meanwhile I activated wireguard, then I started refreshing apps but it didn't finish and the app froze. 
I installed 2 apps through SideStore, they'll expire in 4 days. Don't know if removing them would help.
Every time I'm opening the app it freezes after appx 4-5 seconds. 
Tried to reinstall sidestore, side server, tried the 5.2 beta, it still freezes. 

### Instructions to reproduce

Not sure, can't reproduce it anymore

### What version of SideStore are you using?

5.1

**Comment by naturecodevoid** [comment]
If you can't reproduce, why did you open the issue?

**Comment by alx080** [comment]
> If you can't reproduce the issue anymore, why did you open the issue?

The app freezes every time i launch it.
If that's what you mean: yes I can reproduce the error simply by launching the app.

**Comment by naturecodevoid** [comment]
Any logs or crash reports?
Have you even tried a fresh install?

**Comment by alx080** [comment]
Yes, what I found is that SideStore doesn't freeze when there's no internet connection.
SideStore freezes after 5-7 seconds when I'm on WiFi (TP Link Router, 1.1.1.1 DNS over https). 
Turning off WiFi and using mobile data works somehow.
Interestingly, the first time I used SideStore, it didn't freeze on WiFi.
Only error in the log, but I don't think that it's connected to the app freeze:
"13:08:52 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError"

**Comment by alx080** [comment]
When trying to install an app it uses the App ID but hangs up here and gives me the error to use WireGuard and a WiFi connection (Im on mobile data as the app still freezes on wifi): 
![IMG_5551](https://github.com/SideStore/SideStore/assets/95551024/34580cd2-f729-4dae-93cc-c5e2f328bd16)

**Comment by g3orgeH** [comment]
The app freezes for me as well even after a uninstall and reinstall, I have notice that when I try to debug it the minimuxer section is still scrollable when it freezes, and the loading symbol keeps playing, I can provided screen recording and the debug logs I got if this helps with resolving the issue.

Im using an iPhone 8
Latest iOS 16.7.11 version

Im starting to think it's after I install a few sources to sidestore that i get the issue or it might be the modded youtube I install each time, besides that, idk why this is happening only on my iPhone 8 and not on my iPad pro.

And just like this guy, it only happens when I allow the annie set server to connect with the vpn and with an internet connection.
If I turn off the VPN, the app work's fine, but obviously I can't refresh my apps.
As it crashes in about 5 seconds after launching i believe this to be a minimuxer, thing but I don't know what it does to be quite honest, but it's the only thing which is interactable when it freezes.
https://photos.app.goo.gl/wnPEdM1wf8rZg8WX9
Video of me showing off the freezing.
BTW I'm on sidestore 0.6.1


Edit: I just reinstalled the app with a different apple ID and it doesn't freeze now, I aint touching sources in case it starts freezing again, i'm manual installing apps from now on.
