### ISSUE TITLE
[BUG] Freeze after a few seconds iPadOS 16.7.8 iPad Pro 9.7-inch

### ISSUE THREAD

**Issue by LuigiHackFan** [SideStore/SideStore#625]
### Describe the bug

Whenever I try to use side store, it will just freeze after a few seconds. For some reason this does not seem to happen when the VPN is disabled. The iPad also gets pretty warm when SideStore freezes. I've seen multiple users having the same issue with older versions but I have the latest one (0.5.6) which seems to have this problem again. Could it be just be the A9?

### Instructions to reproduce

Launch SideStore with VPN enabled and try to install an app with an iPad Pro 9.7-inch

### What version of SideStore are you using?

0.5.6

**Comment by auralluring** [comment]
been having this issue for a bit on my iPhone 8. originally it was like this for a week, then i reinstalled sidestore (because of #560) and the bug was gone for another week, but i just reinstalled again and it's back.

if i'm fast enough i can sometimes refresh an app before it freezes, but installing anything new is basically impossible.

**Comment by iamjhe08** [comment]
> I also had this issue. Checking the log, it was the Developer Disk image that caused the issue. For devices running iOS 16.7.6 to 16.7.8, minimuxer couldn't download the corresponding DMG.
> 
> I am currently opening a pull request on [jkcoxson/JitStreamer](https://github.com/jkcoxson/JitStreamer) so that those iOS version will be using 16.4's DMG like iOS 16.7.5 and lower. For now, there is a workaround for this problem. Let me know if it works!
> 
> 1. Download the [iOS 16.4 Developer Disk image](https://github.com/jawshoeadan/Xcode_Developer_Disk_Images/releases/download/16.4/16.4.zip) (thanks jawshoeadan!).
> 2. Extract the archive and rename both the files inside to your iOS version.
> 3. Copy those two files to `On My iPhone/SideStore/DMG`.

Dude. I've been looking for an answer for this issue with my iphone X ios 16.7.15 and I can confirm that this method works since the latest sidestore "refresh all apps shortcut" is not working so I downgraded to  0.5.8 but it has freezing issues, so I followed your method and man it works 100%. I'm happy that I can refresh my apps especially dopamine. Again. Thanks a ton man.
