### ISSUE TITLE
[BUG] The operation couldn’t be completed. AFC was unable to manage files on the device

### ISSUE THREAD

**Issue by Wei-Winter** [SideStore/SideStore#648]
### Describe the bug

When I try to install an IPA or refresh SideStore, I encounter this error. I have tried restarting the device, resetting the pairing files, and reinstalling SideStore, but the issue still persists. I don't know what to do.

### Instructions to reproduce

I encounter this error when installing an IPA or refreshing SideStore.

### What version of SideStore are you using?

0.5.6

**Comment by JayceTheBased** [comment]
Did you sideload Sidestore with altserver? Use that as opposed to sideserver if you didn't already - sideserver started giving me this same problem a while ago IIRC.

**Comment by polymo1** [comment]
> Use that as opposed to sideserver if you didn't already -

Yes, please! SideServer is currently not in a functional state, and should not be used.

**Comment by polymo1** [comment]
I remember seeing this mentioned before: do you have the widget on your homescreen? If you do, remove that, restart SideStore, then try again.

**Comment by junepark678** [comment]
@Wei-Winter AFC errors are usually pairing issues, please generate a new pairing and install it into SideStore.

**Comment by junepark678** [comment]
Closing for now...

**Comment by control0forver** [comment]
Maybe you forgot to start StosVPN before installing from SideStore?

**Comment by l-e-a-n** [comment]
I had to actively Reset Pairing File in settings, and then refresh it. Refreshing over existing did not work.

**Comment by Kofa1** [comment]
Tried different pairing files, didn't work. Removed the previous ones from the app.

**Comment by pradeeps2001** [comment]
This same issue is also occurring for me. This is the error shown when trying to refresh.
"The operation couldn’t be completed. AFC was unable to manage files on the device. This usually means an invalid pairing."

I tried every actions below,
1. idevice_pair is not even installing in my mac it shows like “idevice_pair.app” was not opened because it contains malware. This action did not harm your Mac. And moves it to bin.
2. So I tried using jitterbugpair and generated new pairing file many times that also didn't fix.
3. Tried resetting the anisette servers.
4. Tried changing the Ip address in wireguard VPN.
5. Restarted the sidestore/device many times.

What else can I do to fix this issue?

**Comment by ghost** [comment]
wireguard is not supported on 0.6.2+
