### ISSUE TITLE
Unable to Connect To VPN/ AFC Unable to Manage Files

### ISSUE THREAD

**Issue by arandomidiot2** [SideStore/SideStore#657]
### Describe the bug

Upon opening SideStore, making sure the WireGuard VPN is on I get the error _Unable to connect to the device, make sure WireGuard is enabled and you’re connected to WiFi_ even though WireGuard is on and I’m on WiFi | Upon trying to refresh apps using the shortcut in the shortcuts app the shortcuts app says that it was unable to manage profiles on the device; And in SideStore I get the error; _The operation couldn’t be completed. AFC was unable to manage files on the device_

### Instructions to reproduce

Go to into SideStore; Turn on WireGuard and try to refresh apps | Go into Shortcuts app and run the _“Refresh all apps”_ Shortcut.

### What version of SideStore are you using?

0.5.6

**Comment by fish4terrisa-MSDSM** [comment]
Refresh the jitterbug pair file(Regenrate it on your computer, mine is archlinux with jitterbugpair-linux), and restart sidestore(It will tell you to do so)
At first it may still refuse to refresh apps, use the shortcut to force it.And, if you want to sideload new app, long press the + button on the upper-left corner.(Worked on my ipad pro m4)

**Comment by Tvred6** [comment]
> Refresh the jitterbug pair file(Regenrate it on your computer, mine is archlinux with jitterbugpair-linux), and restart sidestore(It will tell you to do so) At first it may still refuse to refresh apps, use the shortcut to force it.And, if you want to sideload new app, long press the + button on the upper-left corner.(Worked on my ipad pro m4)

What is jitterbugpair-linux vs the normal file? And what shortcut  can you use to force them to install?

**Comment by Hakanaydin10** [comment]
I had the same mistake, I really tried a lot. Everything that was actually on the internet and I had added such a widget from Sidestore so that I can see how many days I have left to update. Thought it worked before and not now, then I deleted the widget and suddenly it worked. Try it out.  if it worked, liked my comment so that more people can find the error immediately.

**Comment by fish4terrisa-MSDSM** [comment]
Regenrate your jitterbugpair file(run the jitterbugpair binary with idevice connected to the computer, just like what the manual told you to do), and import it to SideStore(Delete the origin one) If the problem still exists, maybe you can send the minimuxer logs in 'View Error logs'(simply press the bug icon on the right corner of the page) and I'll have a look of it.(In most situations, it's related with heartbeat problems, which is often caused by pairing files)

**Comment by fish4terrisa-MSDSM** [comment]
> > Refresh the jitterbug pair file(Regenrate it on your computer, mine is archlinux with jitterbugpair-linux), and restart sidestore(It will tell you to do so) At first it may still refuse to refresh apps, use the shortcut to force it.And, if you want to sideload new app, long press the + button on the upper-left corner.(Worked on my ipad pro m4)
> 
> What is jitterbugpair-linux vs the normal file? And what shortcut can you use to force them to install?

There's no difference between the pairing file generated by jitterbugpair-linux and the files generated by other platforms. However, sometimes they may suddenly  refuse to work any longer(Often caused by pairing the idevice to another computer) Then you have to regenerate the pairing file.
To import the pairing file, simply press the button 'Delete ***  pairing ***' in the setting section of SideStore(Sorry, I've forgetten the exact location or name of this button... My ipad is running UTM and very **HOT** at this time and I'm afraid that opening SideStore will kill the poor VM XD)

**Comment by Hakanaydin10** [comment]
https://github.com/user-attachments/assets/887694d3-474b-47c5-b56d-6d122ee35151

![IMG_6576](https://github.com/user-attachments/assets/4434cdd1-5c94-4cf3-973b-cfe4f6776c00)

**Comment by Hakanaydin10** [comment]
I tried everything with the file as I said, but only this helped me with the error

https://github.com/user-attachments/assets/b0eb9dda-6363-462f-bec8-553aa52be611

![IMG_6575](https://github.com/user-attachments/assets/2abf2730-2eba-4cc2-bd14-3c9c566e3e5c)
![IMG_6583](https://github.com/user-attachments/assets/4e3156ee-41d6-4383-b239-8fcf499051cf)

**Comment by fish4terrisa-MSDSM** [comment]
> I tried everything with the file as I said, but only this helped me with the error
> 
>  RPReplay_Final1723108490.mp4 
> ![IMG_6575](https://private-user-images.githubusercontent.com/177801253/356160103-2abf2730-2eba-4cc2-bd14-3c9c566e3e5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjkyMzAsIm5iZiI6MTcyMzYyODkzMCwicGF0aCI6Ii8xNzc4MDEyNTMvMzU2MTYwMTAzLTJhYmYyNzMwLTJlYmEtNGNjMi1iZDE0LTNjOWM1NjZlM2U1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwOTQ4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDQ4MjFhOGQ1MjY1ZTNjZDNjODA0MWI0ZWEzZWZjYzIyOTQ3OGY1NzJlYThjZGI3NmI3ZWE2OGQ1OWIyOGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eAW4bxEE1tyaqQc0Ztob9okQ5S0JSSKcy2osJYRFeyI) ![IMG_6583](https://private-user-images.githubusercontent.com/177801253/356160116-4e3156ee-41d6-4383-b239-8fcf499051cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjkyMzAsIm5iZiI6MTcyMzYyODkzMCwicGF0aCI6Ii8xNzc4MDEyNTMvMzU2MTYwMTE2LTRlMzE1NmVlLTQxZDYtNDM4My1iMjM5LThmY2Y0OTkwNTFjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwOTQ4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDE3MzAyZjI2OWE1NjM5Nzk0MTc0ZmNkZjQ1NTI3ZTc0OGIxMzVmNDM5ZjRlNzQyMzUzY2ExNjgxY2I4NDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BhOZGRTFAn3onOs4ZG_3nHwahU9xAzpCIHf99xqR93g)

Please send a screenshot about the log showed after pressing the 'bug' icon on the top-right corner of the "Error log" window.

**Comment by junepark678** [comment]
Please use a new pairing, these issues are usually an issue with an expired pairing :)
