### ISSUE TITLE
[BUG] « Refresh All Apps » Shortcuts Refresh all apps except SideStore

### ISSUE THREAD

**Issue by ShadowWLX** [SideStore/SideStore#713]
### Describe the bug

I used the function Refresh All Apps on Shortcuts but when executing the shortcut it Refresh all apps except SideStore Even if i add a long time to wait after the « Refresh All Apps » function.

The shortcut is good so the error is probably on what the « Refresh All Apps » do.

### Instructions to reproduce

Just follow this tutorial who explain how to make the shortcut. https://youtu.be/16gZztB8E2U?si=lulh-JgE8elegYkR

### What version of SideStore are you using?

0.5.8

### Other info

When i go to « View Refresh Attempts » i have a failure, « the operation was cancelled » on the automatic shortcut executing but when i execute the shortcut my self or i Refresh the apps manually i don’t have any News on the Refresh history

**Comment by KaaaooS** [comment]
Is a current bug,some people say 0.5.6 version works fine with the shortcut

**Comment by Kazagumo** [comment]
you have to make sure the wireguard still connected longer then shortcuts notifying you that all apps had refreshed.
just put a wait function between refresh and disconnect and 60s delay time is practically stable.

**Comment by mahee96** [comment]
Yeah as Kazagumo said the refresh notifies within seconds that it has completed but takes almost 50 seconds to finish. If VPN is disconnected before that, then it will indeed fail with “Operation was cancelled”


Background and Shortcut refresh has been fixed in PR#743. 

Note: the shortcut says refresh is done but sidestore reinstall happens at almost 40+ seconds…

In rare cases the refresh says “done” but sidestore won’t actually reinstall and in Refresh Attempts one can see “Operation was cancelled 1002”

So wait for a minute after attempting refresh via shortcut for full refresh to happen

After refresh one should have “success” message as this one

![6BB54E43-62E9-4E65-85D4-70D0D956CEE5](https://github.com/user-attachments/assets/a57d97b8-83a5-42ea-82f6-fa746cf4f2cf)

**Comment by justreportingissues** [comment]
How is this STILL not fixed?
