### ISSUE TITLE
[BUG] OperationError 1013 (Shortcut Refresh does not work)

### ISSUE THREAD

**Issue by pakjinho12** [SideStore/SideStore#723]
### Describe the bug

There is no problem when I press Refresh All directly in the sidestore, but when I use Refresh All using a shortcut, OperationError 1013 occurs and the refresh does not work.
![KakaoTalk_20241028_111042826](https://github.com/user-attachments/assets/4d922820-05a8-4aad-8176-b17f5571e877)
![KakaoTalk_20241028_111042826_01](https://github.com/user-attachments/assets/b8f5a369-fab8-4d0d-b5e0-5391e32bbc34)
![KakaoTalk_20241028_111042826_02](https://github.com/user-attachments/assets/d467235b-193e-4c24-9c84-7181f3e010be)

### Instructions to reproduce

when I use Refresh All using a shortcut, OperationError 1013 occurs and the refresh does not work.

### What version of SideStore are you using?

0.5.9-nightly.2024.10.17.1+867a9c7

**Comment by mahee96** [comment]
This must be related to the background refresh failure case too.

**Observations**:  OperationError.InvalidParameters 1013 are common in both issue so both issues are taking same code path and ending up at possibly same error.

Needs a fix soon since this affects background refresh too

**Comment by mahee96** [comment]
@pakjinho12, can you install the next nightly and report us back with the error Log screen. It must have more info now which will help us fix the issue.

**Comment by pakjinho12** [comment]
@mahee96,  나이트 버전 0.5.9-nightly.2024.11.09.1+1174126  을 설치해도 여전히 단축어로 자동 리프레시가 되지 않습니다.

하지만 전과는 다른 오류 메시지가 확인됩니다.

Invalid parameters:
AppManager._install.removeAppExtensionsOperati
on: context.app or
context.authenticatedContext.presentingViewCont
roller is nil

첨부된 사진을 참고해 주시면 감사하겠습니다.

![IMG_9120](https://github.com/user-attachments/assets/08f391d4-5603-4628-8464-6a787c81d7ee)
![IMG_9121](https://github.com/user-attachments/assets/bcb17047-e143-4e43-9172-058294fec1f4)

**Comment by mahee96** [comment]
I think this is enough info for us to fix the issue. Thanks for getting back

**Comment by mahee96** [comment]
@pakjinho12 can you try to install again the youtube app via normal install “+” button, this will reinstall on top and won’t delete existing app data.

When doing this please choose which app extensions you need. If you don’t need anything then choose “remove all extensions”.

The fix for #696 should work but needs one to reinstall the apps they have previously installed to remove the existing app extensions that were chosen to be removed.

**Comment by mahee96** [comment]
![image](https://github.com/user-attachments/assets/c1e3670d-5b14-4ad8-afec-d78276e9c5d0)

  
  
 AppManager.refresh() when after performing RefreshOperation and if there is an error of type  
 1. ALTServerError.unknownRequest or
 2. OperationError.appNotFound(name: app.name). 
   
 falls back to installation.   
   
     
But during installation the app extensions removal handling requires a UI context and if one is not provided then it will fail with "Invalid Parameters" error. 

Now we need to know why the Refresh operation failed in first place, if it was due to ALTServerError.unknownRequest or OperationError.appNotFound to fix the issue at root cause.

**Comment by mahee96** [comment]
![image](https://github.com/user-attachments/assets/ba03dbf1-651d-427a-aa35-1dc630533295)


Okay, found another interesting observation.  

Sidestore refresh operation takes install path when app was installed via PC/Mac aka first install, this includes installation from Xcode

**Comment by mahee96** [comment]
It is clearly evident that the following code in AppManager.perform() uses install path when it can't use refresh path as usual due to following conditions.
```swift
                case .refresh(let app):
                    // Check if backup app is installed in place of real app.
                    let uti = UTTypeCopyDeclaration(app.installedBackupAppUTI as CFString)?.takeRetainedValue() as NSDictionary?

                    if app.certificateSerialNumber != group.context.certificate?.serialNumber ||
                        uti != nil ||
                        app.needsResign ||
                        // We need to reinstall ourselves on refresh to ensure the new provisioning profile is used
                        app.bundleIdentifier == StoreApp.altstoreAppID
                    {
                        // Resign app instead of just refreshing profiles because either:
                        // * Refreshing using different certificate
                        // * Backup app is still installed
                        // * App explicitly needs resigning
                        // * Device is jailbroken and using AltDaemon on iOS 14.0 or later (b/c refreshing with provisioning profiles is broken)
                        
                        let installProgress = self._install(app, operation: operation, group: group) { (result) in
                            self.finish(operation, result: result, group: group, progress: progress)
                        }
                        progress?.addChild(installProgress, withPendingUnitCount: 80)
                    }
                    else
                    {
                        // Refreshing with same certificate as last time, and backup app isn't still installed,
                        // so we can just refresh provisioning profiles.
                        
                        let refreshProgress = self._refresh(app, operation: operation, group: group) { (result) in
                            self.finish(operation, result: result, group: group, progress: progress)
                        }
                        progress?.addChild(refreshProgress, withPendingUnitCount: 80)
                    }
                    
```

1st Refresh of sidestore immediately after first install: 
(lldb) po group.context.certificate?.serialNumber
▿ Optional<String>
  - some : "7A237E614B4863B95B0FB69E4B01B71F"  

(lldb) po app.certificateSerialNumber
nil

2nd Refresh of sidestore:
(lldb) po app.certificateSerialNumber
▿ Optional<String>
  - some : "7A237E614B4863B95B0FB69E4B01B71F"
    
(lldb) po group.context.certificate?.serialNumber
▿ Optional<String>
  - some : "7A237E614B4863B95B0FB69E4B01B71F"

But,
(lldb) po app.bundleIdentifier == StoreApp.altstoreAppID
true
(lldb) po StoreApp.altstoreAppID
"com.SideStore.SideStore"
(lldb) po app.bundleIdentifier
"com.SideStore.SideStore"


Sidestore app is always set to install fresh intentionally. 
```swift
                // We need to reinstall ourselves on refresh to ensure the new provisioning profile is used
                app.bundleIdentifier == StoreApp.altstoreAppID
```

All other apps take refresh path when refresh is requested. 


So there must be 2 ways this can happen, 
1. App refresh is requested via background/shortcut and it takes refresh path but ends up into install path as per comment https://github.com/SideStore/SideStore/issues/723#issuecomment-2466474169
2. App refresh is requested via background/shortcut but it takes install path since sidestore is also included and prematurely exiting since the "removeAppExtensions" requires UI context and background/shortcuts doesn't have one. 


**Fix is simple:** Ignore remove appExtensions when there is No UI context instead of considering it as error scenario in install Path. 

But we still need to confirm our hypothesis by testing the mentioned scenarios before drafting a fix.

**Comment by pakjinho12** [comment]
@mahee96, I reinstalled the YouTube app by pressing the + button as requested.

I chose to remove all extensions in the extension app selection and tried refreshing via the shortcut after the installation was complete, but it still didn't work.

Please refer to the attached picture.
Thank you.
![IMG_9126](https://github.com/user-attachments/assets/54be7196-9cb0-4b37-a4d8-cf79d389194d)
![IMG_9125](https://github.com/user-attachments/assets/63cd8a33-76de-4e68-ae71-f7ac1a2f72cb)
![IMG_9124](https://github.com/user-attachments/assets/3c1eeb1c-3564-4700-9f44-4b2ea1c33706)

**Comment by pakjinho12** [comment]
@mahee96, I installed the new night version on November 10th and tried the same thing again.

I'm attaching a picture of the error log.
![IMG_9127](https://github.com/user-attachments/assets/54602a01-5d45-44ca-94c3-fa65c8506f35)

**Comment by mahee96** [comment]
@pakjinho12 it will not resolve the issues fully but will fix one of the issue.

if you notice there are 2 errors in your comment 1013 and 1018, by doing a “install” the error 1018 should no longer occur as expected.

Issue with error code 1013 is still under investigation

**Comment by mahee96** [comment]
@pakjinho12 , try the latest [nightly](https://github.com/SideStore/SideStore/suites/30716018803/artifacts/2168611813) and see if the background refresh and shortcut based refresh works.

Both are expected to work and you should see a "success" message under "Refresh Attempts" screen in Settings screen.

**Comment by mahee96** [comment]
Feel free to re-open the issue if issue is still reproducible with the nightly build mentioned in the above comment
