### ISSUE TITLE
[BUG]  SideStore App ID missing 

### ISSUE THREAD

**Issue by dylans509** [SideStore/SideStore#744]
### Describe the bug

The SideStore App ID is not showing up on the App ID  section and I can’t refresh my apps. I’m also afraid SideStore expires after the 7 day period and I already deleted the apps, and I'm wondering if SideStore refreshes after the 7 day period the app is will come back
![IMG_0276](https://github.com/user-attachments/assets/c76cc4c3-0c59-4c69-8e4f-f2e25e79a7a8)

### Instructions to reproduce

I don't have the SideStore App ID

### What version of SideStore are you using?

0.5.8

**Comment by mahee96** [comment]
Yeah this is a rare case when sidestore didn’t get a chance to refresh the provisioning profile but then the user tried to install a new app and it failed due to max 3 app id limit or passed, in both cases the user is left without anymore AppIDs which makes refreshing sidestore impossible within that next x days window until an app id slot becomes free…

if sidestore is scheduled to expire before that window then “yes” sidestore will be gone and needs to be reinstalled
